name: Update GitHub Profile Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history

      - name: Fetch Full History
        run: git fetch --unshallow

      - name: Detect README Changes
        id: check_readme
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "github-profile/README.md"; then
            echo "README_CHANGED=true" >> $GITHUB_ENV
          else
            echo "README_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Exit if README not changed
        if: env.README_CHANGED == 'false'
        run: echo "No README changes detected, skipping profile update." && exit 0

      - name: Set Up Git
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"

      - name: Clone GitHub Profile Repo
        run: |
          git clone "${{ secrets.REPO_GITHUB_PROFILE_URL }}" profile_repo

      - name: Sync GitHub Profile Content
        run: |
          rsync -av --delete github-profile/ profile_repo/

      - name: Clean Up README
        run: |
          sed -i '/^> \[!NOTE\]/{N;d;}' profile_repo/README.md

      - name: Check for Uncommitted Changes
        run: |
          cd profile_repo
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            echo "Changes detected, proceeding with commit..."
          fi

      - name: Commit and Push Changes
        run: |
          cd profile_repo
          COMMIT_MSG=$(git -C ../ show -s --format=%B HEAD)
          git commit -m "Sync GitHub profile (README update): $COMMIT_MSG"
          git push origin main